global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "dataflow-ingestion"
    static_configs:
      - targets: ["ingestion-service:9090"]
        labels:
          service: "dataflow"
